exclude: ^(profiling/|tests/data/)
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: pip-freeze
        name: Update requirements.txt
        entry: bash -c 'pip freeze > backend/requirements.txt'
        language: system
        files: \.py$
        always_run: true
        pass_filenames: false
