import clsx from 'clsx';

import ClientProver from '@/components/ClientProvider';
import Layout from '@/components/Layout';

import pretendardFont from './_fonts';

import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function RootLayout({ children }: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko" className={clsx(pretendardFont.className, 'light')}>
      <body>
        <ClientProver>
          <Layout>
            {children}
          </Layout>
        </ClientProver>
      </body>
    </html>
  );
}

export default RootLayout;
