name: Frontend CI

on:
  pull_request:
    branches: [main]
    paths: 'frontend/**'
  push:
    branches: [main]
    paths: 'frontend/**'

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Check Lint
        if: ${{ github.event_name == 'pull_request' }}
        run: yarn lint
